
###Variable global
@api = http://localhost:8001/products
@http = HTTP/1.1


GET {{api}} HTTP/1.1

###
POST {{api}} HTTP/1.1
Content-Type: application/json

{
    "name": "Webcam Ryzer",
    "description": "WebCam usb"
    
}


###

GET {{api}}/1000


###
DELETE {{api}}/8


###
POST {{api}}/total


###Update a product

PUT {{api}}/1
Content-Type: application/json

{
    "name": "Laptop",
    "description": "Lenovo Gamming G5",
    "quantity": 200

}